PLF-6993: Update README.txt, Release Notes and Changelog for PLF 4.4.0
exoplatform/platform-public-distributions pull request #121
Opened 2016-12-02 13:41 UTC by mgreau

This PR has been created to work on the Release Notes, Changelog and README files for PLF 4.4.0.

For now, I've done the following:

- [x] README.txt:  update HTTP link for eXo Platform documentation
- [x] CHANGE_LOG.txt : remove 4.3.x features,fix and improvement
- [x] RELEASE_NOTES : Prepare the `Main changes since Platform 4.3` part

The following parts have to be updated/created:

- CHANGE_LOG.txt
    - [ ] New features
    - [ ] Improvement
    - [ ] Bug

- RELEASE_NOTES 
    - [ ]  Main changes since Platform 4.3 > Features
    - [ ]  Main changes since Platform 4.3 > eXo Add-ons
    - [ ]  Main changes since Platform 4.3 > Upgrade
    - [ ]  Main changes since Platform 4.3 > Bugs fixes
    - [ ]  IV. KNOWN ISSUES

2016-12-20 21:04 UTC, thomasdelhomenie commented
Changelogs have been updated with issues list and release notes have been updated with upgrade notes and architecture changes.
The only remaining item is Know Issues. I don't have in mind any new know issues to add in the list, but we should check if the already listed know issues are still issues in 4.4.0.

2016-12-21 10:17 UTC, plamarque requested changes
see my comments

2016-12-21 10:17 UTC, plamarque commented on plf-packaging-resources/src/main/resources/CHANGE_LOG.txt
> +    * ECMS-7431 - upgrade ITHIT to v2.0.1735.0
[Open in Office] upgrade ITHit to 2.0.1735.0

2016-12-21 10:17 UTC, plamarque commented on plf-packaging-resources/src/main/resources/CHANGE_LOG.txt
> +    * SOC-5351 - Make people search tolerant to accents and typos
accents and typos insensitive

2016-12-21 10:17 UTC, plamarque commented on plf-packaging-resources/src/main/resources/CHANGE_LOG.txt
> +    * PFR-1116 - Forum Redesign
overstatement. a more accurate summary would be : [Forum] Mobile friendly topic list

2016-12-21 10:17 UTC, plamarque commented on plf-packaging-resources/src/main/resources/RELEASE_NOTES.txt
> +** New file storage (File RDBMS)
can we regroup technical features at the bottom of the list ?

2016-12-21 10:17 UTC, plamarque commented on plf-packaging-resources/src/main/resources/RELEASE_NOTES.txt
> +Since the version 4.4.0, eXo Platform needs Elasticsearch.
/s/needs/requires

2016-12-21 10:17 UTC, plamarque commented on plf-packaging-resources/src/main/resources/RELEASE_NOTES.txt
> +Exo Platform is provided with an embedded version of Elasticsearch which automatically starts when eXo Platform starts.
**e**Xo Platform is **shipped**

2016-12-21 11:23 UTC, thomasdelhomenie commented on plf-packaging-resources/src/main/resources/CHANGE_LOG.txt
> +    * ECMS-7431 - upgrade ITHIT to v2.0.1735.0
I used the jira issue summary as is so I will update jira issues as well.

2016-12-21 13:46 UTC, thomasdelhomenie commented on plf-packaging-resources/src/main/resources/CHANGE_LOG.txt
> +    * ECMS-7431 - upgrade ITHIT to v2.0.1735.0
Done

2016-12-21 13:46 UTC, thomasdelhomenie commented on plf-packaging-resources/src/main/resources/CHANGE_LOG.txt
> +    * SOC-5351 - Make people search tolerant to accents and typos
Done

2016-12-21 13:46 UTC, thomasdelhomenie commented on plf-packaging-resources/src/main/resources/CHANGE_LOG.txt
> +    * PFR-1116 - Forum Redesign
Done

2016-12-21 13:46 UTC, thomasdelhomenie commented on plf-packaging-resources/src/main/resources/RELEASE_NOTES.txt
> +** New file storage (File RDBMS)
Done

2016-12-21 13:46 UTC, thomasdelhomenie commented on plf-packaging-resources/src/main/resources/RELEASE_NOTES.txt
> +Since the version 4.4.0, eXo Platform needs Elasticsearch.
Done

2016-12-21 13:46 UTC, thomasdelhomenie commented on plf-packaging-resources/src/main/resources/RELEASE_NOTES.txt
> +Exo Platform is provided with an embedded version of Elasticsearch which automatically starts when eXo Platform starts.
Done

2016-12-23 14:03 UTC, merged