PLF-7286 : change log level for logger org.apache.catalina.realm.JAASRealm to avoid displaying a stacktrace for each failed login
exoplatform/platform-public-distributions pull request #144
Opened 2017-06-19 20:13 UTC by thomasdelhomenie

Throwing an exception is expecting when there is a login failure, as defined in [JAAS doc](http://docs.oracle.com/javase/8/docs/technotes/guides/security/jaas/JAASLMDevGuide.html). The exception is logged by Tomcat (we do not have this behavior with JBoss), so the best and simplest thing to do is to change the log level of JAAS class to ERROR.

2017-06-19 21:01 UTC, fdrouet requested changes
The problem with your solution is that it hide an important information that I want to keep : the fact that someone failed to login and the login string.

It should be possible to swallow the stack trace at log framework level to only keep the exception message.

2017-06-19 21:45 UTC, thomasdelhomenie commented
There are actually 2 logs from 2 classes : one which displays the single warn line and one which displays the stack trace. This PR only removes the stack trace.

2017-06-20 14:52 UTC, thomasdelhomenie commented
@fdrouet is that ok for you ?

2017-06-21 07:20 UTC, fdrouet commented
That is ok for me If we keep the login fail info

2017-06-21 07:21 UTC, fdrouet approved these changes

2017-06-21 11:14 UTC, boubaker approved these changes

2017-06-22 07:01 UTC, merged